package com.cg.OnlineBusBooking.controllers;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

import javax.transaction.Transactional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

import com.cg.OnlineBusBooking.entities.Bus;
import com.cg.OnlineBusBooking.entities.BusOperator;
import com.cg.OnlineBusBooking.entities.BusOperatorRequest;
import com.cg.OnlineBusBooking.serviceinterfaces.IAdminService;

@RestController
@RequestMapping(path = "/admin") //URL specification before every method
public class AdminController {
	
	//Dependency Injection
	@Autowired
	IAdminService adminService;
	
	//REST Method to return all Bus Operators
	@GetMapping("/getall")
	@ResponseStatus(HttpStatus.FOUND)
	public List<BusOperator> getAllBusOperator(){
		return adminService.getAllBusOperator();
	}
	
	//REST Method to return all Bus Operators from a specific Bus Route
	@GetMapping("/getbyroute/{route}")
	@ResponseStatus(HttpStatus.FOUND)
	public List<BusOperator> getAllBusOperatorByRoute(@PathVariable("route")String route){
		return adminService.getAllBusOperatorByRoute(route);
	}
	
	//REST Method to return all Bus Operator Requests
	@GetMapping("/getrequest")
	@ResponseStatus(HttpStatus.FOUND)
	public List<BusOperatorRequest> getAllBusOperatorsRequest(){
		return adminService.getAllBusOperatorsRequest();
	}
	
	//REST Method to update journey duration of a specific booking
	@PutMapping("/updatetime/{bookingId}/{startTime}/{endTime}")
	@Transactional
	@ResponseStatus(HttpStatus.CREATED)
	public void updateBusTime(@PathVariable("bookingId") long bookingId,@PathVariable("startTime")String startTime,@PathVariable("endTime") String endTime) {
		LocalTime startTime1 = LocalTime.parse(startTime);
		LocalTime endTime1 = LocalTime.parse(endTime);
		adminService.updateBusTime(bookingId, startTime1, endTime1);
	}
	
	//REST Method to update Bus Route of a bus
	@PutMapping("/updatebusroute/{route}")
	@Transactional
	@ResponseStatus(HttpStatus.CREATED)
	public void updateBusRoute(@RequestBody Bus bus,@PathVariable("route") String route) {
		adminService.updateBusRoute(bus, route);
	}
	
	//REST Method to update bus fare of a specific bus
	@PutMapping("/updatebusfare/{fare}")
	@Transactional
	@ResponseStatus(HttpStatus.CREATED)
	public void updateBusFare(@RequestBody Bus bus,@PathVariable("fare") int fare) {
		adminService.updateBusFare(bus, fare);
	}
	
	//REST Method to delete a specific bus
	@DeleteMapping("/deletebus/")
	@ResponseStatus(HttpStatus.OK)
	public void deleteBus(@RequestBody Bus bus) {
		adminService.deleteBus(bus);
	}
	
	//REST Method to delete a specific bus by the Bus Operator
	@DeleteMapping("/deletebyoperator/{operator}")
	@ResponseStatus(HttpStatus.OK)
	public void deleteBusByOperator(@PathVariable("operator")String operator) {
		adminService.deleteBusByOperator(operator);
	}
	
	//REST Method to get the revenue generated by a bus on a certain date
	@GetMapping("getrevenuebydate/{date}")
	@ResponseStatus(HttpStatus.FOUND)
	public int getRevenueByDate(@PathVariable("date") String date) {
		LocalDate date1 = LocalDate.parse(date);
		return adminService.getRevenueByDate(date1);
	}
	
	//REST Method to get the revenue generated by a bus from a specific bus route
	@GetMapping("/getrevenuebybusroute/{route}")
	@ResponseStatus(HttpStatus.FOUND)
	public int getRevenueByBusRoute(@PathVariable("route") String route) {
		return adminService.getRevenueByBusRoute(route);
	}
	
	//REST Method to get the revenue generated by a bus by a specific bus operator
	@GetMapping("/getrevenuebybusoperator/{busOperatorUsername}")
	@ResponseStatus(HttpStatus.FOUND)
	public int getRevenueByBusOperator(@PathVariable("busOperatorUsername") String busOperatorUsername) {
		return adminService.getRevenueByBusOperator(busOperatorUsername);
	}

}
